services:
  opencode:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: opencode

    restart: unless-stopped

    tty: true
    stdin_open: true

    ports:
      - "4096:4096"

    environment:
      - TZ=America/Bogota

      # Seguridad Web UI
      - OPENCODE_SERVER_USERNAME=${OPENCODE_USER}
      - OPENCODE_SERVER_PASSWORD=${OPENCODE_PASS}
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4096/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

      
    volumes:
      - opencode-home:/home/opencode

      # Acceso Docker host
      - /var/run/docker.sock:/var/run/docker.sock

      # SSH persistente
      - ~/.ssh:/home/opencode/.ssh

      # Workspace persistente
      - /opt/workspaces:/workspace

volumes:
  opencode-home:
