services:
  opencode:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: opencode

    restart: unless-stopped

    tty: true
    stdin_open: true

    ports:
      - "4096:4096"
      - "37701:37701"
    environment:
      - TZ=America/Bogota
      - CLAUDE_MEM_RUNTIME=worker
# Recomendado: configurar en Coolify como Secret 
      - CLAUDE_MEM_PROVIDER=openrouter 
      - CLAUDE_MEM_OPENROUTER_API_KEY=${CLAUDE_MEM_OPENROUTER_API_KEY}
# Seguridad Web UI
      - OPENCODE_SERVER_USERNAME=${OPENCODE_USER}
      - OPENCODE_SERVER_PASSWORD=${OPENCODE_PASS}
    
    extra_hosts:
      - "coolify.metabiblioteca.com.co:135.125.150.34"
      - "host.docker.internal:host-gateway" 
      - "koha.local:10.0.0.15"
      - "dspace.local:10.0.0.20"
      
    volumes:
      - opencode-home:/home/opencode

      # Acceso Docker host
      - /var/run/docker.sock:/var/run/docker.sock

      # SSH persistente
      - ~/.ssh:/home/opencode/.ssh

      # Workspace persistente
      - /opt/workspaces:/workspace

volumes:
  opencode-home:
